Ryu1234-tech/freemarket_sample_64b

app/assets/stylesheets/sign_up.scss, app/assets/stylesheets/users/sign_up.scss, app/views/sign_up/_footer.haml, app/views/sign_up/done.haml, app/views/sign_up/index.html.haml, app/views/users/sign_up/_footer.haml, app/views/users/sign_up/adress.haml, app/views/users/sign_up/payment.haml, app/views/users/sign_up/registration.haml, app/views/users/sign_up/sms_confirmation.html.haml, app/views/users/sign_up/sms_confirmed.haml
新規登録、ログインページ一連のページの実装。
本アプリをログインして使うためのページを実装。
=> registorview

app/assets/stylesheets/logout.scss, app/views/logout/index.haml
ログアウトページの実装をした。
ログイン、ログアウトの機能があるため、ユーザーが適切にログアウトできるページが必要であるから。
ログアウトページのスクショです。
https://gyazo.com/5205e42eff2496fb2b5b7ed23ce15509
ヘッダー、ヘッダー下のナビ、サイドバー、フッターは後ほどマイページとともに送ります。
=> ログアウトページの実装

Gemfile.lock, app/views/devise/sessions/new.haml
what
Gemfile.lockを一度消した
why
omniauthを消したかったため
=> omniauth警告文のチェック

app/assets/javascripts/payjp.js, app/assets/javascripts/posts.coffee, app/assets/javascripts/transactions.coffee, app/controllers/card_controller.rb, app/views/card/step5.haml, config/initializers/assets.rb
=> [WIP]クレジットカード登録機能の編集

app/assets/stylesheets/mypage.scss, app/views/mypage/profile.haml
プロフィール編集ページの実装。
自己紹介文を編集できるページを実装しました。
スクショです。
https://gyazo.com/e285d297b93315025a7b3d54036d473e
=> プロフィール編集ページの実装

Gemfile.lock, config/routes.rb
=> topページの表示ルーティングの設定

app/assets/javascripts/birthday.js, app/models/birthyear.rb, config/locales/ja.yml
・月別に日数が変わる
・閏年の設定
ユーザーが誤って存在しない誕生日を入力するのを防ぐため
=> [WIP]誕生日入力の条件分け実装

app/controllers/users/omniauth_callbacks_controller.rb, app/controllers/users/registrations_controller.rb
・omniauthコントローラーの編集
sessionへ直接代入
・registrations_controllerの編集
パスワード自動生成をキャンセル
・session[:uid]、session[:provider]からDB登録されるように修正
SNS認証から登録されないエラーを修正するため
=> [WIP]SNS認証の修正

app/assets/stylesheets/_exhibit_logo.scss, app/controllers/items_controller.rb, app/views/items/index.html.haml, app/views/mypage/index.html.haml, app/views/shared/_exhibit_logo.html.haml
出品ロゴの実装
itemコントローラーの記述ミス削除
出品ページへのリンクを作成するため
=> 出品ロゴの実装commit1

app/assets/stylesheets/transactions/done.scss, app/views/transactions/done.haml
取引が完了した後の今後の流れなどが説明してあるページの実装
ユーザーがスムーズに取引を進めるために必要なページ。
=> 取引完了ページの実装

app/assets/javascripts/item_new.js, app/assets/stylesheets/_itemnew.scss, app/controllers/items_controller.rb, app/views/items/new.html.haml, app/views/shared/_exhibit_logo.html.haml, db/migrate/20191212081059_create_images.rb
・item_new.jsファイルの記述
・_itemnew.scssファイルの追記
・new.html.hamlファイルの追記
・画像投稿前に確認を可能にするため
・複数投稿を可能にするため
=> [WIP]商品新規投稿時の画像プレビュー表示

app/controllers/users/registrations_controller.rb, app/views/mypage/_sidebar.html.haml, app/views/mypage/profile.haml, config/routes.rb
What
マイページからプロフィール編集への遷移を可能にした
ついでにコントローラー内のsns.saveも削除した
Why
現状遷移だけ可能な状態にできたので、先に上げておきました
sns.saveに関しては、新規登録時にエラーの原因となったので消しました
=> [WIP] マイページからの遷移

app/views/mypage/_sidebar.html.haml, app/views/mypage/identification.html.haml, app/views/shared/_top_page_header.html.haml, config/routes.rb
What
・ローカルホストに飛ぶ記述をprefixを参考に記述変更
・hamlの命名を統一
Why
・本番でもローカルホストに飛んでしまう記述となっていたので修正
・コントローラーで読みにいく際に、ビューが見つからなくなってしまうから
=> [WIP]ルーティング設定

app/assets/stylesheets/mypage/profile.scss, app/views/mypage/identification.html.haml, app/views/mypage/profile.haml
What
サイドバーをレンダーさせたらviewが崩れたのでそこの修正をしました
Why
見た目を整えるため
=> [WIP]プロフィールVIEWの修正

app/assets/stylesheets/mypage/sidebar.scss, app/views/mypage/_sidebar.html.haml
What
サイドバーで以下の項目を追加しました
・出品する
・購入した商品-取引中
Why
不足箇所があったため
=> サイドバーの項目追加

app/controllers/mypage_controller.rb, app/views/mypage/add.haml, app/views/mypage/card.html.haml, app/views/mypage/identification.html.haml, config/routes.rb
what
支払い方法の項目からカード登録に飛べるようにした
why
ルーティングができていなかったので
=> マイページからの遷移2

Gemfile, Gemfile.lock, app/assets/stylesheets/_breadcrumbs.scss, app/assets/stylesheets/mypage/credit_card.scss, app/assets/stylesheets/mypage/exhibit.scss, app/assets/stylesheets/mypage/logout.scss, app/assets/stylesheets/mypage/mainbox.scss, app/views/layouts/application.html.haml, app/views/mypage/card.html.haml, app/views/mypage/identification.html.haml, app/views/mypage/index.html.haml, app/views/mypage/logout.haml, app/views/mypage/profile.haml, config/breadcrumbs.rb
What
gem "gretel"導入
すでに作成されている以下のVIEWページのパンくず実装の
.マイページ
.プロフィール
.カード
.本人情報の登録
.ログアウト
Why
使いやすくするため
=> [WIP]パンくず作成

app/assets/stylesheets/_item_show.scss, app/controllers/items_controller.rb, app/controllers/mypage_controller.rb, app/views/items/show.html.haml, app/views/mypage/_mainbox.html.haml, config/routes.rb
・商品詳細ページのバグ修正
・その他表示の微修正
最新画像・最古画像の表示で出るバグの修正
=> 商品詳細修正commit1

app/controllers/items_controller.rb
トップページカテゴリー対応idの修正
カテゴリーidを仮置きしていたので修正
=> トップページ修正commit1

app/assets/javascripts/item_new.js, app/views/items/show.html.haml
・item_new.jsファイルの修正
・items/show.haml
・コード短縮のため
・投稿後エラー改善のため
=> [WIP]新規商品出品JS修正

app/controllers/items_controller.rb, app/views/items/edit.haml
=> 商品詳細ページcommit1

Gemfile, app/models/category.rb, app/models/item.rb, db/migrate/20191220045729_create_categories.rb, db/migrate/20191220052119_add_ancestry_to_categories.rb, db/schema.rb, db/seeds.rb, spec/factories/categories.rb, spec/models/category_spec.rb
カテゴリーを細分化するためにancestryを導入した。
カテゴリーをわかりやすく細分化するため
=> ancestryの導入

app/controllers/items_controller.rb, app/controllers/mypage_controller.rb, app/controllers/sign_up_controller.rb
各コントローラーのアクションについて、アクセス制限をかけた。
ログインしていない状態でアクセスを試みると、ログインページにリダイレクトされるよう実装した。
登録済みユーザーのみアクセス可能なページを選別するため。
=> [WIP]認証されていないユーザーのアクセス制限

app/views/devise/registrations/_footer.haml, app/views/devise/registrations/step1.haml, app/views/devise/registrations/step2.haml, app/views/devise/registrations/step3.haml, app/views/sign_up/_login_footer.haml, app/views/sign_up/_login_simple_header.haml, app/views/sign_up/done.haml, app/views/sign_up/index.haml, app/views/user_address/step4.haml
#What
ヘッダーのロゴを押したらトップページに飛べるように修正
#Why
ワンクリックでトップに飛べるようにするため
=> 新規登録のヘッダー画面の修正

app/assets/stylesheets/devise/registrations.scss, app/assets/stylesheets/sign_up/done.scss, app/views/items/new.html.haml, app/views/sign_up/done.haml
リンクとビューが少々崩れていたため修正
ちゃんとした動作をさせるため
=> リンクとビューの修正

app/assets/stylesheets/mypage/identification.scss, app/views/mypage/_sidebar.html.haml, app/views/mypage/identification.html.haml
What
本人情報の登録ページの県名選択のf.select追加
サイドバーの出品ボタンのルート追加
=>  本人情報の登録ページのprefectureのselectの追加

app/controllers/items_controller.rb, app/views/items/buy.haml, app/views/items/done.haml, config/routes.rb
#What
購入者が購入の際に住所を表示させて住所が確認できるようにする。
#Why
誤った住所に商品が届かないように確認するため。
=> 購入者のクレジットカード、住所の表示

app/assets/stylesheets/_top_page_body.scss, app/assets/stylesheets/item/_item_show.scss, app/controllers/items_controller.rb, app/views/items/_top_page_body.html.haml, app/views/items/show.html.haml
items/show.hamlとindex.hamlの条件分岐
購入ボタンを押すと該当itemにbuyer_idが振られる
購入済み商品を二重購入不可にするため
=> [WIP]出品中と購入済みの判定

Gemfile, Gemfile.lock, app/assets/javascripts/item_edit.js, app/assets/javascripts/item_new.js, app/controllers/card_controller.rb, app/controllers/items_controller.rb, app/views/items/edit.haml, app/views/layouts/application.html.haml
itemの編集画面へ行けるようにした
payjpのAPIをcredential.ymlから読めるようにした。
画面のレビューをしてもらうため
=> [WIP]item編集機能

app/controllers/mypage_controller.rb, app/views/mypage/profile.haml
what
プロフィールページのユーザー名のboxにカレントユーザー名を表示させるようにした
=> プロフィールのカレントユーザー名表示

app/controllers/items_controller.rb
items_controllerの編集
ログインしていないユーザーのアクセス制限をかけるため
=> [WIP]ログインしていないユーザーが商品一覧・商品詳細以外のページへ行こうとしたらログインページへリダイレクトさせる

app/controllers/items_controller.rb
items_controllerの編集
堅牢なWebアプリケーションの実装をするため
=> [WIP]様々なアクセス制限
